# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RapOff' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RapOff
   pod 'web3swift'
   pod 'UInt256', :git => 'https://github.com/hyugit/UInt256.git'
   pod 'WalletConnectSwiftV2'







post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            end
        end
    end
end

end
